In [1]:
import keras
import tensorflow as tf
import sys
sys.path.append('..')

In [2]:
from src.model.components import MultiHeadAttentionStack, PoolingAttentionBlock, MLP

In [3]:
input = keras.layers.Input(shape=(8,4))
attention = MultiHeadAttentionStack(3, 4)(input, input)
pooling = PoolingAttentionBlock(4, 1)(attention)
output = MLP(1, activation="sigmoid")(pooling)
output = keras.layers.Flatten()(output)


model = keras.models.Model(inputs=input, outputs=output)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [4]:
dummy_data = tf.random.normal((500, 8, 4))
labels = tf.random.uniform((500, 1), maxval=2, dtype=tf.int32)
model.predict(dummy_data)

16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 117ms/step


array([[0.45323473],
       [0.4517846 ],
       [0.4621425 ],
       [0.462898  ],
       [0.46322292],
       [0.44969118],
       [0.45088476],
       [0.44876432],
       [0.45499113],
       [0.44907722],
       [0.45158917],
       [0.44930974],
       [0.45118156],
       [0.45355698],
       [0.4525294 ],
       [0.45701092],
       [0.4503712 ],
       [0.45571244],
       [0.44790936],
       [0.45676062],
       [0.4500593 ],
       [0.46395686],
       [0.46312526],
       [0.45083758],
       [0.44807735],
       [0.4607553 ],
       [0.45521206],
       [0.4676987 ],
       [0.45415604],
       [0.45036834],
       [0.45016643],
       [0.4583981 ],
       [0.46514428],
       [0.45167455],
       [0.450517  ],
       [0.46321294],
       [0.46319088],
       [0.45453134],
       [0.45802698],
       [0.4514178 ],
       [0.4635775 ],
       [0.4540354 ],
       [0.45740515],
       [0.4473007 ],
       [0.45137978],
       [0.45509493],
       [0.48738053],
       [0.451

In [5]:
model.fit(dummy_data, labels, epochs = 10)
model.predict(dummy_data)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 21s 33ms/step - accuracy: 0.5080 - loss: 0.6938
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5260 - loss: 0.6909
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5360 - loss: 0.6901
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5600 - loss: 0.6891
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5440 - loss: 0.6877
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5620 - loss: 0.6854
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5820 - loss: 0.6846
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5700 - loss: 0.6826
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5940 - loss: 0.6803
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5900 - loss: 0.6778
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[0.50687337],
       [0.5011407 ],
       [0.482838  ],
       [0.50687337],
       [0.50687337],
       [0.39954886],
       [0.49584174],
       [0.38722593],
       [0.50687337],
       [0.4025761 ],
       [0.4295583 ],
       [0.38829035],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.40971234],
       [0.50687337],
       [0.3861395 ],
       [0.48811436],
       [0.45712796],
       [0.50687337],
       [0.47881705],
       [0.48132455],
       [0.3898708 ],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.45874265],
       [0.41883865],
       [0.50687337],
       [0.50687337],
       [0.41019428],
       [0.39871272],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.45988306],
       [0.50687337],
       [0.4244802 ],
       [0.50687337],
       [0.37999138],
       [0.39967537],
       [0.50687337],
       [0.50687337],
       [0.462

In [6]:
model.save('test_model.keras')

In [7]:
test = keras.models.load_model('test_model.keras', custom_objects={'MultiHeadAttentionStack': MultiHeadAttentionStack, "MLP": MLP, "PoolingAttentionBlock": PoolingAttentionBlock})

In [8]:
test.predict(dummy_data)

16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step


array([[0.50687337],
       [0.5011407 ],
       [0.482838  ],
       [0.50687337],
       [0.50687337],
       [0.39954886],
       [0.49584174],
       [0.38722593],
       [0.50687337],
       [0.4025761 ],
       [0.4295583 ],
       [0.38829035],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.40971234],
       [0.50687337],
       [0.3861395 ],
       [0.48811436],
       [0.45712796],
       [0.50687337],
       [0.47881705],
       [0.48132455],
       [0.3898708 ],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.45874265],
       [0.41883865],
       [0.50687337],
       [0.50687337],
       [0.41019428],
       [0.39871272],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.50687337],
       [0.45988306],
       [0.50687337],
       [0.4244802 ],
       [0.50687337],
       [0.37999138],
       [0.39967537],
       [0.50687337],
       [0.50687337],
       [0.462